import { FlatCompat } from '@eslint/eslintrc';

/**
 * Flat config for apps/web (CI TODO 2026-08: "add an eslint flat-config to
 * apps/web, then drop continue-on-error").
 *
 * Policy: Errors gate CI; warnings stay visible but non-blocking. The 250+
 * existing warnings are a triage backlog, not an overnight fix — they are
 * dominated by `no-unused-vars` (dead imports + deliberate `_`-prefixed
 * ignores) and `react-hooks/exhaustive-deps` (real audit targets). Sweeping
 * them silently would risk exactly the churn the CLAUDE.md surgical-changes
 * rule forbids; they get fixed in review-sized batches instead.
 */
const compat = new FlatCompat({
  baseDirectory: import.meta.dirname,
});

export default [
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    rules: {
      // `_x` is the codebase's established deliberate-ignore prefix.
      '@typescript-eslint/no-unused-vars': [
        'warn',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      // Audit target, not a gate: 31 live sites, each needs a real
      // dependency-array decision, not a mechanical append.
      'react-hooks/exhaustive-deps': 'warn',
    },
  },
  // Generated, vendor, and Playwright trees never lint:
  //  - .next/ + next-env.d.ts are regenerated by `next` (triple-slash refs are next's own output);
  //  - e2e/ runs under Playwright, not React render — next's rules-of-hooks fires
  //    false positives on its `use()`-shaped fixture helpers there.
  { ignores: ['.next/**', 'node_modules/**', 'public/**', 'next-env.d.ts', 'e2e/**'] },
];
