/**
 * Render the modelGatewayContractRegistry as a human-readable per-model parameter
 * MATRIX (execution plan DoD 10). Generated from the registry so the committed doc
 * (docs/platform/model-gateway-contract-matrix.md) can never drift from the contracts — a
 * sync test fails CI if the doc is stale. Columns show, per (model, gateway, mode),
 * exactly what each route accepts and how it normalizes: the FE-control → serialized
 * surface. The billed-selector and delivered-output columns arrive with the
 * billed==served invariant (Phase 4) and live spot-checks.
 */

import type { ModelGatewayContract } from './model-contract';

function enumCell(
  param: { values: readonly string[]; default: string; onInvalid: string } | undefined,
): string {
  if (!param) return '—';
  return `${param.values.join(', ')} · def \`${param.default}\` · ${param.onInvalid}`;
}

function durationCell(c: ModelGatewayContract): string {
  const d = c.duration;
  if (!d) return '—';
  const steps = d.steps ? `[${d.steps.join(', ')}]` : 'any';
  const intermediate = d.acceptsIntermediate ? '+intermediate' : 'snap-only';
  return `${steps} · ${d.min}–${d.max}s · ${intermediate} · <min:${d.onBelowMin} >max:${d.onAboveMax}`;
}

function referenceCell(c: ModelGatewayContract): string {
  const r = c.reference;
  if (r.imageRole === 'none') return 'none';
  if (r.imageRole === 'frame') return `frames [${r.frameRoles.join(', ')}]`;
  const imageCap = r.maxImages > 0 ? `img≤${r.maxImages}` : 'img (max unverified)';
  return `refs ${imageCap}${r.maxVideos ? ` vid≤${r.maxVideos}` : ''}${
    r.maxAudios ? ` aud≤${r.maxAudios}` : ''
  }`;
}

function audioCell(c: ModelGatewayContract): string {
  if (!c.audio.output) return 'none';
  return c.audio.control ? 'output+control' : 'output only';
}

/** Neutralize table-breaking characters so a stray pipe/newline in future contract
 * data can't silently corrupt the table while the sync test still passes. */
function escapeCell(value: string): string {
  return value.replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
}

/** One markdown table row per contract. */
function contractRow(c: ModelGatewayContract): string {
  return [
    c.modelId,
    c.gateway,
    c.inputMode,
    c.role,
    `\`${c.slug}\``,
    enumCell(c.resolution),
    enumCell(c.aspectRatio),
    durationCell(c),
    referenceCell(c),
    audioCell(c),
    c.negativePrompt ? 'yes' : 'no',
    `${c.provenance.source} ${c.provenance.date}`,
  ]
    .map((cell) => escapeCell(String(cell)))
    .join(' | ');
}

const HEADER = [
  'Model',
  'Gateway',
  'Mode',
  'Role',
  'Slug',
  'Resolution',
  'Aspect',
  'Duration',
  'Conditioning',
  'Audio',
  'NegPrompt',
  'Provenance',
];

/**
 * Render the full matrix markdown. Deterministic: models in the given key order,
 * primary route before fallback within each model, so the committed doc is stable.
 */
export function renderContractMatrix(
  registry: Readonly<Record<string, readonly ModelGatewayContract[]>>,
): string {
  const lines: string[] = [];
  lines.push('<!-- GENERATED by renderContractMatrix — do not hand-edit; run the sync test. -->');
  lines.push('# Model × gateway parameter matrix');
  lines.push('');
  lines.push('One row per `(model, gateway, inputMode)` route contract, generated from the');
  lines.push('modelGatewayContractRegistry (`packages/shared/src/model-contract-byteplus.ts`).');
  lines.push('This is the authoritative accepted-parameter surface each route serializes; a');
  lines.push('drift between this doc and the registry fails CI (the sync test).');
  lines.push('');
  lines.push(`| ${HEADER.join(' | ')} |`);
  lines.push(`| ${HEADER.map(() => '---').join(' | ')} |`);
  for (const routes of Object.values(registry)) {
    const ordered = [...routes].sort((a, b) =>
      a.role === b.role ? 0 : a.role === 'primary' ? -1 : 1,
    );
    for (const c of ordered) lines.push(`| ${contractRow(c)} |`);
  }
  lines.push('');
  return lines.join('\n');
}
