#!/usr/bin/env bash
# Migration-gated, health-gated deploy (INF-15 / INF-16).
#
# Order matters: apply DB migrations BEFORE routing traffic to the new build, so
# the new code never sees an old schema. If migrations fail, abort — do not
# deploy. After start, wait for /ready (deps up) before declaring success.
#
# This is the compose flavour; the same sequence maps to k8s (a migrate Job that
# gates the Deployment rollout + a readinessProbe on /ready).
#
# Env:
#   SEED_IMAGE_TAG   tag to deploy (default: full git sha)             [recorded for rollback]
#   SEED_ENV_FILE    env file with secrets + DATABASE_URL (INF-13)
#   SEED_SITE_ADDRESS production hostname for Caddy auto-TLS (required)
#   DATABASE_URL     used by the migration step (from the env file)
#   SEED_REGISTRY    when set (e.g. cr.yandex/<id>), PULL prebuilt images from the
#                    registry instead of building on the host, and run migrations
#                    inside the api image (no host pnpm/toolchain needed). This is
#                    the CI/CD path; unset keeps the local `--build` path.
#   SEED_COMPOSE_OVERRIDE optional additional compose file for VM-local topology
#                    (for example, a local state network override); unset on
#                    managed-state hosts.
set -euo pipefail

# The edge must have a real site address before migrations or a rollout begin.
# Without this guard Compose silently fell back to :8080: the app/worker stayed
# healthy, but the public hostname had no TLS site and browser traffic failed.
: "${SEED_SITE_ADDRESS:?SEED_SITE_ADDRESS is required for production edge TLS (e.g. vertov.space)}"

COMPOSE_ARGS=(docker compose -f infra/compute/docker-compose.app.yml)
if [[ -n "${SEED_COMPOSE_OVERRIDE:-}" ]]; then
  COMPOSE_ARGS+=(-f "$SEED_COMPOSE_OVERRIDE")
fi
compose() { "${COMPOSE_ARGS[@]}" "$@"; }
TAG="${SEED_IMAGE_TAG:-$(git rev-parse HEAD)}"
export SEED_IMAGE_TAG="${TAG}"
LAST_DEPLOYED_TAG_FILE="${SEED_LAST_DEPLOYED_TAG_FILE:-.last-deployed-tag}"
READY_ATTEMPTS="${DEPLOY_READY_ATTEMPTS:-30}"
READY_INTERVAL_SECONDS="${DEPLOY_READY_INTERVAL_SECONDS:-2}"

log() { printf '[deploy %s] %s\n' "$(date -u +%H:%M:%S)" "$*" >&2; }

# Keep the last known-good image identity before doing anything that can replace
# the running containers. The file is written only after a successful readiness
# gate, so it is a rollback pointer rather than a claim that a deploy started.
PREVIOUS_TAG=""
if [ -s "${LAST_DEPLOYED_TAG_FILE}" ]; then
  read -r PREVIOUS_TAG <"${LAST_DEPLOYED_TAG_FILE}" || true
  # The value is generated by this script, but fail closed if an operator or a
  # damaged disk left a value that cannot be a Docker tag.
  if [[ ! "${PREVIOUS_TAG}" =~ ^[A-Za-z0-9][A-Za-z0-9_.-]*$ ]]; then
    log "ignoring invalid previous tag in ${LAST_DEPLOYED_TAG_FILE}"
    PREVIOUS_TAG=""
  fi
fi

# Pre-warm the self-hosted ASR model so the FIRST user's auto-captions aren't a
# cold start — the first transcription otherwise downloads (~244MB) + loads the
# model. Hits the loopback whisper port; best-effort, NEVER fails the deploy, and
# doubles as a smoke test of the captions path. (Note: WHISPER__TTL=-1 to keep the
# model resident is NOT usable — it 404s the API in faster-whisper-server 0.6.0-rc.4.)
prewarm_whisper() {
  [ -f infra/compute/warmup.wav ] || return 0
  log "pre-warming whisper (loads/downloads the model)…"
  if curl -fsS -m 300 -o /dev/null \
      -F file=@infra/compute/warmup.wav \
      -F "model=${WHISPER_MODEL:-Systran/faster-whisper-small}" \
      -F response_format=json \
      http://127.0.0.1:8088/v1/audio/transcriptions; then
    log "whisper warm ✅"
  else
    log "whisper pre-warm skipped (non-fatal; first caption request will warm it)"
  fi
}

wait_ready() {
  for i in $(seq 1 "${READY_ATTEMPTS}"); do
    if curl -fsS http://127.0.0.1:4000/ready >/dev/null 2>&1; then
      return 0
    fi
    sleep "${READY_INTERVAL_SECONDS}"
  done
  return 1
}

rollback_previous() {
  if [ -z "${PREVIOUS_TAG}" ] || [ "${PREVIOUS_TAG}" = "${TAG}" ]; then
    log "no distinct previous-good tag is available for automatic rollback"
    return 1
  fi

  log "readiness failed for ${TAG}; restoring previous good tag ${PREVIOUS_TAG}"
  export SEED_IMAGE_TAG="${PREVIOUS_TAG}"
  if [ -n "${SEED_REGISTRY:-}" ]; then
    log "pulling previous images for rollback…"
    if ! compose pull api web; then
      log "FATAL: could not pull rollback images for ${PREVIOUS_TAG}"
      return 1
    fi
  fi
  if ! compose up -d --remove-orphans; then
    log "FATAL: could not start rollback tag ${PREVIOUS_TAG}"
    return 1
  fi
  if wait_ready; then
    echo "${PREVIOUS_TAG}" >"${LAST_DEPLOYED_TAG_FILE}"
    prewarm_whisper
    log "rollback restored readiness ✅ (tag ${PREVIOUS_TAG})"
    return 0
  fi
  log "FATAL: rollback tag ${PREVIOUS_TAG} did not become ready"
  return 1
}

log "deploying tag ${TAG}${SEED_REGISTRY:+ from ${SEED_REGISTRY}}"

# 0) DISK HYGIENE (INF) — BEFORE pulling the new image set, drop every image +
#    build-cache layer NOT used by a running container. The currently-deployed
#    set stays (its containers are up), so this never touches the live stack; it
#    just clears the OLD tags that piled up from past deploys. Bounds on-disk
#    images at ~2 sets (current + the one we're about to pull) and prevents the
#    "no space left on device" that aborted a pull on the 30 GB VM. Rollback to
#    an older tag is always a re-pull — registry images are immutable.
if [ -n "${SEED_REGISTRY:-}" ]; then
  log "pruning unused images + build cache (disk hygiene)…"
  docker image prune -af >/dev/null 2>&1 || true
  docker builder prune -f >/dev/null 2>&1 || true
  df -h / | awk 'NR==2{printf "[deploy] disk: %s used of %s (%s free)\n",$3,$2,$4}' >&2 || true
fi

# 1) Get the images for this tag — pull from the registry (CI/CD) or build locally.
if [ -n "${SEED_REGISTRY:-}" ]; then
  log "pulling images…"
  compose pull api web
else
  log "building images…"
  compose build
fi

# 2) MIGRATION GATE — apply migrations before any new container serves traffic.
#    Forward-only; rollback of a bad migration is a restore (see backup runbook).
#    On the registry path the host has no toolchain, so migrate inside the image.
log "applying DB migrations (gate)…"
if [ -n "${SEED_REGISTRY:-}" ]; then
  migrate() { compose run --rm --no-deps api pnpm db:migrate; }
else
  migrate() { pnpm db:migrate; }
fi
if ! migrate; then
  log "FATAL: migrations failed — aborting deploy (no traffic shifted)"
  exit 1
fi

# 3) Roll the services. Compose waits for healthchecks before marking healthy;
#    the edge depends_on api/web service_healthy, so traffic shifts only when
#    /health passes (INF-16).
log "starting new containers…"
if ! compose up -d --remove-orphans; then
  log "FATAL: new tag ${TAG} failed to start"
  if rollback_previous; then
    log "service restored to ${PREVIOUS_TAG}; deploy remains failed"
  else
    log "automatic rollback failed or was unavailable"
  fi
  exit 1
fi

# 4) Readiness gate — block until the API reports deps-ready (or fail).
log "waiting for /ready…"
if wait_ready; then
  log "ready ✅ (tag ${TAG})"
  echo "${TAG}" >"${LAST_DEPLOYED_TAG_FILE}"
  prewarm_whisper
  exit 0
fi

# Compose has replaced the app containers by this point. Recover the last
# successful image when one exists, but still exit non-zero so the deploy job
# reports the bad release rather than hiding it behind a green rollback.
if rollback_previous; then
  log "FATAL: tag ${TAG} failed readiness; service restored to ${PREVIOUS_TAG}"
else
  log "FATAL: /ready never went green and automatic rollback failed or was unavailable"
fi
exit 1
